version: "3.9"
services:

  nginx:
    container_name: nginx
    build: nginx/
    ports:
      - "80:80"
    networks:
      internal_routes:

  rabbitmq_create_user:
    image: rabbitmq 
    ports:
      - "5672:5672"
    networks:
      internal_routes:
        aliases:
          - rabbitmq
  
  create_user:
    build: create_user/
    networks:
      internal_routes:
        aliases:
          - create_user

  list_user:
    container_name: api_luser
    build: list_user/
    links: 
      - "mongodb_slave"
    networks:
      internal_routes:
        aliases:
          - list_user

  data:
    build: data/
    depends_on:
      - "rabbitmq_create_user"
    restart: on-failure
    networks:
      internal_routes:

  mongodb_master:
    container_name: mongo_master
    image: mongo

  mongodb_slave:
    container_name: mongo_slave
    image: mongo

networks:
  internal_routes:
